apiVersion: apps/v1
kind: Deployment
metadata:
  name: h5-q4-stable
  labels:
    app: h5-q4
    type: stable
    version: v1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: h5-q4
      type: stable
  template:
    metadata:
      labels:
        app: h5-q4
        version: v1
        type: stable
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo:1.0.0
          args:
            - "-listen=:5678"
            - "-text=stable v1"
          ports:
            - containerPort: 5678